version: '3.1'

services:

  mongo:
    image: mongo
    container_name: pub_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: db_replenishment
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pub123
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d