version: '3.1'

services:

  db:
    image: postgres
    container_name: pub_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pub123
      POSTGRES_DB: db_analysis
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d