version: '3.1'

services:

  db:
    image: mysql
    container_name: pub_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pub123
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d